<font size='6'>TUGAS NUMPY DASAR</font><br><br>

<font size='3'>
Muhammad Audri Indraputra<br>
Kelas Ragnarok<br>
Rabu, 9 Maret 2022<br></font>

---

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [7, 8]])
B = np.array([[3, 5], [1, 6]])

In [3]:
print('2 * A =\n', 2 * A,'\n')
print('2 + A =\n', 2 + A,'\n')
print('A + B =\n', A + B,'\n')
print('A - B =\n', A - B,'\n')
print('Determinan A :\n', np.linalg.det(A),'\n')

2 * A =
 [[ 2  4]
 [14 16]] 

2 + A =
 [[ 3  4]
 [ 9 10]] 

A + B =
 [[ 4  7]
 [ 8 14]] 

A - B =
 [[-2 -3]
 [ 6  2]] 

Determinan A :
 -6.0 



In [4]:
D = np.linalg.inv(B)
print('Invers B = D, D ialah :\n', D, '\n')
print('Transpose D :\n', np.transpose(D),'\n')

print('Nilai Eigen A :\n',np.linalg.eig(A)[0],'\n')
print('Vektor Eigen A :\n', np.linalg.eig(A)[1],'\n')

print('Nilai Eigen B :\n',np.linalg.eig(B)[0],'\n')
print('Vektor Eigen B :\n', np.linalg.eig(B)[1],'\n')

Invers B = D, D ialah :
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]] 

Transpose D :
 [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]] 

Nilai Eigen A :
 [-0.62347538  9.62347538] 

Vektor Eigen A :
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]] 

Nilai Eigen B :
 [1.8074176 7.1925824] 

Vektor Eigen B :
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]] 

